on: [ push, pull_request ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.10", "3.9", "3.8", "3.11"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-dev.txt
          python -m pip install .
          python -m pip install tox
          git clone https://github.com/json5/json5-tests.git

      - name: Test with coverage/pytest
        env:
          PYTHONUNBUFFERED: "1"
        run: |
          tox -e py
      - name: Coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install --upgrade coveralls
          coveralls --service=github
